# Generated by Django 3.2.15 on 2022-08-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('measurement_unit', models.CharField(max_length=16, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
