version: '3.3'
services:
  
  frontend:
    image: oitczvovich/frontend_foodgram:v0.1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
 
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: oitczvovich/backend_foodgram:v0.1
    restart: always
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
    - db
    - backend
    - frontend

volumes:
  static_value:
  media_value:
  postgres_data: