# Generated by Django 3.2.15 on 2022-08-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
