# Generated by Django 3.2.15 on 2022-10-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_follow_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-id'], 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
